# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Delectus Vinum"
description: > # this means to ignore newlines until "email:"
   Sélection fine de vins de qualité

   Nous proposons une sélection de vins de qualité pour tous.
   Notre credo est que derrière chaque bouteille il y a un viticulteur, un vigneron, un oenologue, toute une famille parfois, … dont la passion est de sublimer dans nos verres ce que la nature peut nous offrir de mieux. Notre volonté est d’aller à la rencontre de tous ces passionnés afin de connaître l’histoire de chacune de leur création. Et notre plus grand plaisir est de partager cela avec vous.
   Nos critères de sélection sont la qualité, le plaisir et le respect.
   La qualité est une simple évidence.
   Le plaisir c’est la convivialité des dégustations, le partage avec vous des vins que nous aimons.
   Le respect c’est d’abord celui de la nature qui nous offre cette boisson millénaire mais aussi celui du client en pratiquant des prix équitables.

   A votre santé !
email: info@delectusvinum.be
#blog logo
logo: "/assets/images/df_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Nicolas Brasseur'
author: 'Nicolas Brasseur'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@nicolasbrasseur'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/nicolasbrasseur
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/delectusvinum
    desc: Connect with us on facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

#  - icon:	github
#    url:	https://github.com/nicolasbrasseur
#    desc:	Fork me on github
#    share_url:
#    share_title:
#    share_link:

